[manager]
layout         = [ 1, 4, 3 ]
sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
linemode       = "none"
show_hidden    = true
show_icons     = true

[preview]
tab_size        = 2
max_width       = 600
max_height      = 900
image_filter    = "triangle"
image_quality   = 75
sixel_fraction  = 15

[opener]
edit = [
	{ run = 'nvim "$@"', block = true, desc = "Edit" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]

[open]
rules = [
	{ name = "*/", use = [ "edit", "open" ] },
	{ mime = "text/*", use = [ "edit", "open" ] },
]
