# AI CLI 統合（Claude Code / OpenAI Codex）
#
# - claude-code / codex は nixpkgs 収録パッケージを使用（npm グローバル運用は廃止）。
# - Claude/Codex の共通コンテキストと各ツール固有設定をリンクする。
{ config, pkgs, ... }:

{
  home.packages = [
    pkgs.claude-code
    pkgs.codex
    pkgs.nodejs_22 # 開発・npm 実行用ランタイム（旧 nvm 廃止の代替）
  ];

  # --- Claude Code / Codex 設定 ---
  # 汎用の AI assistant 設定は git 管理し、個人用の蓄積情報はリポジトリ外に置く。
  # 共通コンテキスト(shared/CONTEXT.md)を single source とし、各ツールのドキュメントへ
  # ビルド時にインラインする（runtime import は使わない）。
  # settings/commands/agents は実行中に即時反映できるよう可変 symlink のまま。
  # 前提: この dotfiles リポジトリが ~/dotfiles に clone されていること。
  home.file =
    let
      claudeDir = "${config.home.homeDirectory}/dotfiles/home/ai/claude";
      # 共通コンテキスト + ツール固有ファイル を合成する
      mkAgentDoc = toolFile: ''
        <!-- This file is generated by Home Manager. -->

        ${builtins.readFile ./shared/CONTEXT.md}

        ${builtins.readFile toolFile}
      '';
    in
    {
      ".claude/CLAUDE.md".text = mkAgentDoc ./claude/CLAUDE.md;
      ".codex/AGENTS.md".text = mkAgentDoc ./codex/AGENTS.md;

      ".claude/settings.json".source =
        config.lib.file.mkOutOfStoreSymlink "${claudeDir}/settings.json";
      ".claude/commands".source =
        config.lib.file.mkOutOfStoreSymlink "${claudeDir}/commands";
      ".claude/agents".source =
        config.lib.file.mkOutOfStoreSymlink "${claudeDir}/agents";
    };
}
