# AI CLI 統合（Claude Code / OpenAI Codex）
#
# - claude-code / codex は nixpkgs 収録パッケージを使用（npm グローバル運用は廃止）。
# - Claude/Codex の共通コンテキストと各ツール固有設定をリンクする。
{ config, pkgs, ... }:

{
  home.packages = [
    pkgs.claude-code
    pkgs.codex
    pkgs.nodejs_22 # 開発・npm 実行用ランタイム（旧 nvm 廃止の代替）
  ];

  # --- Claude Code / Codex 設定 ---
  # 汎用の AI assistant 設定は git 管理し、個人用の蓄積情報はリポジトリ外に置く。
  # 実行中に即時反映・編集できるよう、dotfiles リポジトリへの可変 symlink にする。
  # 前提: この dotfiles リポジトリが ~/dotfiles に clone されていること。
  home.file =
    let
      claudeDir = "${config.home.homeDirectory}/dotfiles/home/ai/claude";
      sharedDir = "${config.home.homeDirectory}/dotfiles/home/ai/shared";
    in
    {
      ".claude/CLAUDE.md".source =
        config.lib.file.mkOutOfStoreSymlink "${claudeDir}/CLAUDE.md";
      ".claude/settings.json".source =
        config.lib.file.mkOutOfStoreSymlink "${claudeDir}/settings.json";
      ".codex/AGENTS.md".text = ''
        <!-- This file is generated by Home Manager. -->

        ${builtins.readFile ./shared/CONTEXT.md}

        ${builtins.readFile ./codex/AGENTS.md}
      '';
      ".claude/shared".source =
        config.lib.file.mkOutOfStoreSymlink "${sharedDir}";
      ".claude/commands".source =
        config.lib.file.mkOutOfStoreSymlink "${claudeDir}/commands";
      ".claude/agents".source =
        config.lib.file.mkOutOfStoreSymlink "${claudeDir}/agents";
    };
}
