# AI CLI 統合（OpenAI Codex）
#
# - codex は nixpkgs 収録パッケージを使用（npm グローバル運用は廃止）。
# - Codex の永続設定・custom agents・skills を git 管理する。
{ config, pkgs, ... }:

{
  home.packages = [
    pkgs.codex
    pkgs.nodejs_22 # 開発・npm 実行用ランタイム（旧 nvm 廃止の代替）
  ];

  # --- Codex 設定 ---
  # 汎用の AI assistant 設定は git 管理し、個人用の蓄積情報はリポジトリ外に置く。
  # AGENTS.md は Home Manager で生成し、config/agents/skills は実行中に即時反映できるよう可変 symlink のまま。
  # 前提: この dotfiles リポジトリが ~/dotfiles に clone されていること。
  home.file =
    let
      codexDir = "${config.home.homeDirectory}/dotfiles/home/ai/codex";
    in
    {
      ".codex/AGENTS.md".text = ''
        <!-- This file is generated by Home Manager. -->

        ${builtins.readFile ./codex/AGENTS.md}
      '';
      ".codex/config.toml".source =
        config.lib.file.mkOutOfStoreSymlink "${codexDir}/config.toml";
      ".codex/agents".source =
        config.lib.file.mkOutOfStoreSymlink "${codexDir}/agents";
      ".agents/skills".source =
        config.lib.file.mkOutOfStoreSymlink "${codexDir}/skills";
    };
}
